## Numpy Data Types
Numpy has a number of different data types available as `np.<data_type>`. The size of data type is platform dependent. The corresponding C data types are:
- np.bool, equivalent to bool
- np.byte, equivalent to signed char
- np.ubyte, equivalent to unsigned char
- np.short, equivalent to short
- np.ushort, equivalent to unsigned short
- np.intc, equivalent to int
- np.uintc, equivalent to unsigned int
- np.int_, equivalent to long
- np.single, equivalent to float
- np.double, equivalent to double

Fixed size data types are also available:
- np.int8, np.int16, np.int32, np.int64
- np.uint8, np.uint16, np.uint32, np.uint64
- np.float32, np.float64
- np.complex64, np.complex128

The above data types can also be used as functions to convert Python's inbuilt data type to Numpy

In [1]:
import numpy as np
small_integer = np.int8(54.0)
small_float = np.float32(32)
print(small_integer)
print(small_float)

54
32.0


Unlike Python's data types, Numpy's data type can over/under flow. Besides the above data types numpy has `np.nan` and `np.inf` to use as filler and infinity value respectively.

## Creating Numpy Arrays
### Convert Python array/tuple

In [4]:
simple_array = np.array([1, 2, 3, 4, 5])
print(type(simple_array))
print(simple_array.dtype)
print(simple_array.shape)

<class 'numpy.ndarray'>
int32
(5,)


In [5]:
np.array([1, 2.0, 'three'])    # everthing upcasted

array(['1', '2.0', 'three'], dtype='<U32')

### Creating Arrays from Special Functions

In [6]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.arange(1, 10, 0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [9]:
np.linspace(1, 10, 50)    # 50 values between 1 and 10

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

### Arrays with Random Values

In [25]:
random_arr = np.random.random(5)
random_2d_arr = np.random.random((2,2))
random_int_arr = np.random.randint(50, 70, 10)    # 10 random ints between 50 and 70
random_2d_int_arr = np.random.randint(10, 20, (2,2))
print(random_arr)
print(random_2d_arr)
print(random_int_arr)
print(random_2d_int_arr)

[0.13288865 0.85589615 0.95342979 0.91255507 0.86834711]
[[0.39807532 0.82746553]
 [0.49784157 0.76389161]]
[59 62 51 62 61 67 53 68 64 51]
[[17 17]
 [12 14]]


There are some useful utility like `np.random.seed` and `np.random.shuffle` which shuffles an existing array.

In [29]:
an_array = np.array([1,2,3,4,5])
np.random.shuffle(an_array)
print(an_array)

[1 3 5 2 4]


### Creating Boolean Arrays

In [12]:
random_2d_arr > 0.5

array([[False, False],
       [False,  True]])

In [39]:
~ (random_2d_arr == 0.6) # ~ stands for not

array([[ True,  True],
       [ True,  True]])

In [40]:
arr_with_nan = np.array([[0, 2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])
np.isnan(arr_with_nan)

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])

### Copy Existing Array

In [13]:
random_arr_copy = random_arr.copy()
print(random_arr_copy)

[0.38515865 0.25097726 0.55149167 0.75063473 0.40390824]


## Miscellaneous Operations
Reshaping a numpy array:

In [15]:
shape1 = np.arange(10)
print(shape1.shape)
shape2 = np.reshape(shape1, (2,5))
print(shape2.shape)
shape1.shape = (5,2)
print(shape1.shape)

(10,)
(2, 5)
(5, 2)


Transposing a numpy array

In [16]:
np.transpose(shape1)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

We can transpose an array of n dimensions, we need to provide `axes` keyword argument.

## Math Operations
Multiple arithmetic operations are supported between
- scalar and array
- array and array
- matrix multiplication

In [17]:
few_numbers = np.arange(10)
few_numbers + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

If we try to do operations on arrays of different dimensions we need to follow broadcasting rules. According to broadcasting rules, we can do operations between matrices having shapes as 1x2x3 and 2x3. In case the dimensions are same then one of the dimensin should be 1, 4x2 and 1x2 are compatible. 

In [18]:
A_ = np.arange(1,10).reshape((3,3))
B_ = np.array([1, 1, 1])
A_ - B_

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
C_ = np.reshape(B_, (1,3))
A_ - C_

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
D_ = np.array([[2, 2, 2]]).reshape((3,1))    # matrix multiplication, dimensions must be MxN and NxP
np.dot(A_, D_)

array([[12],
       [30],
       [48]])

Some other non-linear operations available are:
- np.log
- np.log2
- np.log10
- np.sin and other trignometric operations
- np.exp
- np.exp2

np.e and np.pi are two available constants. Apart from these some statistical operations are also present like
- np.min
- np.max
- np.sum
- np.cumsum
- np.mean
- np.std
- np.var
The above functions also accept `axis` as argument. In a 2d array `axis = 0` means each column, whereas `axis = 1` means each row.

To know the index of minimum or maximum value, use `np.argmin` and `np.argmax`

In [37]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(repr(np.argmin(arr, axis=0)))
print(repr(np.argmin(arr, axis=1)))
print(repr(np.argmax(arr, axis=-1)))

array([2, 0, 1], dtype=int32)
array([2, 2, 0], dtype=int32)
array([1, 1, 1], dtype=int32)


## Indexing
Consider single dimension array as

In [32]:
some_numbers = np.arange(10,21, dtype=np.float32)
some_numbers[[0, 2, 4]]    # pick listed indices

array([10., 12., 14.], dtype=float32)

For multidimensional arrays,

In [35]:
x = np.linspace(5,6,10)
x.shape = (5,2)
print(x)
print(x[1,1])

[[5.         5.11111111]
 [5.22222222 5.33333333]
 [5.44444444 5.55555556]
 [5.66666667 5.77777778]
 [5.88888889 6.        ]]
5.333333333333333


Similar to indexing, we can also slice multidimensional arrays. Remember that a slice is a view into the original array.

In [36]:
print(x[2:4])
print(x[1:3, 1])

[[5.44444444 5.55555556]
 [5.66666667 5.77777778]]
[5.33333333 5.55555556]


## Joining Arrays
- vstack
- hstack
- row_stack: convenience function for hstack
- column_stack: convenience function for vstack
- concatenate

In [42]:
vs1 = np.ones((2,2))
vs2 = np.zeros((3,2))
vs = np.vstack((vs1, vs2))    # vs1 and vs2 must have same number of columns
print(vs)

[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [44]:
hs1 = np.ones((2,3))
hs2 = np.zeros((2,5))
hs = np.hstack((hs1, hs2))    # hs1 and hs2 must have same number of rows
print(hs)

[[1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0.]]
